### ISSUE TITLE
Incorrect Knife Recipes

### ISSUE THREAD

**Issue by brnbrd** [Minecraft-LightLand/Twilight-Delight#1]
Farmer's Delight knives changed crafting recipe format a while back. The knife material is know vertical in the crafting grid with the stick, and not diagonal. The pattern should look like:
"M"
"S"
where M is the material and S is "forge:rods/wooden". Currently, your recipes are diagonal (old format).
Fiery Knife is also missing its crafting recipe from the Iron Knife using Blood Vials. See the recipe for Fiery Sword to understand what I am referencing.

**Comment by lcy0x1** [comment]
thank. I will fix it in next version

**Comment by lcy0x1** [comment]
fixed in v1.2.8
