### ISSUE TITLE
TearDropSword has no texture when using shaderpack

### ISSUE THREAD

**Issue by Ximu-Luya** [Minecraft-LightLand/Twilight-Delight#13]
我了解到有中国的开发者，所以这个issue我用了中文和翻译版本的英文。I know that there are Chinese developers, so I used the Chinese and translated English versions of this issue.

你好，我发现模组中特别添加的刀似乎有自发光贴图/纹理，导致在使用光影时，握在手中的剑或将其仍在地上的掉落物状态时，会完全不展示。我已经确定问题是来自于光影，我关闭光影后一切正常。我非常喜欢这个模组，同时我也非常喜欢使用光影，请问能做一个不会和光影冲突的纹理吗？或者将这样的“修复性”纹理，放进一个额外的数据包中，根据用户需求自行加载，类似与暮色森林中的classic 数据包。如果可以的话，我将感激不尽。
我的Minecraft版本是1.19.2，使用的光影加载器是Oculus1.6.9，使用的光影包是ComplementaryReimagined_r5.0.1，希望这些信息能够帮到你进行测试。

Hello, I noticed that the special added knives in the mod seem to have a self-lighting map/texture, which causes the sword to not be displayed at all when holding it in the hand or when it is still in the dropped object state on the ground when using light and shadow. I've determined that the problem is the light, and everything is fine when I turn it off. I like this module very much, and I also like to use light and shadow, can you make a texture that will not conflict with light and shadow? Alternatively, such "repair" textures can be put into an additional packet that loads itself according to user requirements, similar to the classic packet in the Twilight Forest. I'd appreciate it if you could.
My version of Minecraft is version 1.19.2, and I used a light loader called Oculus1.6.9 and a light package called ComplementaryReimagined_r5.0.1. I hope this information can be useful if you are complementaryReImagined_R5.0.1

![image](https://github.com/Minecraft-LightLand/Twilight-Delight/assets/53012237/6332acaf-30cd-4b8c-b25f-a02f85cb1396)

**Comment by lcy0x1** [comment]
我得学一下怎么加入可选资源包

**Comment by lcy0x1** [comment]
你有办法加入discord或者QQ来讨论测试吗？
Discord: https://discord.gg/BCHNhsDMXz
QQ号689206723

**Comment by Ximu-Luya** [comment]
> 你有办法加入discord或者QQ来讨论测试吗？ Discord: https://discord.gg/BCHNhsDMXz QQ号689206723

好的，已经加QQ群了
