### ISSUE TITLE
[1.20.1] Stat Tinkerer incompatibility

### ISSUE THREAD

**Issue by SigmaFlame** [Minecraft-LightLand/Twilight-Delight#14]
Hello,

In 1.20.1, your mod prevents the mod Stat Tinkerer to work properly.
Your mod seems to enforce that the player revive with 20 hp, even if in Stat Tinkerer I have set to 6 hp.
Removing your mod makes Stat Tinkerer work well again.

https://github.com/Terrails/stat-tinkerer/issues/1

**Comment by lcy0x1** [comment]
I only did `player.setHealth(player.getMaxHealth());`. If they use different max health and player health, I don't think they are doing things properly.

Anyway, you can disable this in config:
in `l2configs/l2library-common.toml`, set
`restoreFullHealthOnRespawn = false`
