### ISSUE TITLE
If you break the pot of firey that contains the dish, the dish inside will disappear.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [Minecraft-LightLand/Twilight-Delight#15]
If you break a Fiery Pot while it has food inside, the Farmer's Delight Pot will be itemized with the items inside the pot preserved, but the Fiery Pot will be itemized with the dishes inside the Fiery Pot gone. Replace the Fiery Namb with a mechanism like the Farmer's Delight pot.

![image](https://github.com/Minecraft-LightLand/Twilight-Delight/assets/157739795/f42f59b3-f962-419f-b4eb-af7af8f202f2)

**Comment by lcy0x1** [comment]
will fix it

**Comment by lcy0x1** [comment]
fixed in 2.0.5
