### ISSUE TITLE
I made an Korean Traslation for this mod

### ISSUE THREAD

**Issue by tankplanelaserkoala** [Minecraft-LightLand/Twilight-Delight#16]
I'm really enjoying this mod. Thank you for making this fun mod. 

[ko_kr.json](https://github.com/Minecraft-LightLand/Twilight-Delight/files/14318094/ko_kr.json)

**Comment by lcy0x1** [comment]
thanks

**Comment by lcy0x1** [comment]
implemented in 2.0.5
