### ISSUE TITLE
Prepositions Capitalized in US Lang

### ISSUE THREAD

**Issue by brnbrd** [Minecraft-LightLand/Twilight-Delight#2]
Minecraft translation convention does not capitalize prepositions such as "of" and "with". Your Registrate name generation is capitalizing these words. Some examples in en_us:
"Plate Of Fiery Snakes" should be "Plate **of** Fiery Snakes"
"Glow Venison Rib With Pasta" should be "Glow Venison Rib **with** Pasta"

**Comment by lcy0x1** [comment]
Seems like Registrate is not smart enough. I will fix it

**Comment by lcy0x1** [comment]
Fixed
