### ISSUE TITLE
Mushgloom Sauce stacks up to 16

### ISSUE THREAD

**Issue by tankplanelaserkoala** [Minecraft-LightLand/Twilight-Delight#20]
Mod Version: 2.0.7

Game Version: 1.20.1

Forge version: 47.2.20

According to the Farmer’s Delight crew, if the dish contained in a bowl serves as an ingredient, it should be stacked 64 times, rather than the 16 times previously thought to be the farmer’s Delight mode cooking rule. 

Change the Mushgloom sauce to stack in stacks of 64.

https://github.com/vectorwing/FarmersDelight/issues/873

**Comment by lcy0x1** [comment]
If that is your concern, I would rather give it some effects lol

What about glowing

**Comment by tankplanelaserkoala** [comment]
I've been thinking about that too. Since it has a luminescent effect, I thought it would be appropriate to overlap 16 of them. However, since Mushgloom Sauce is in the same position as the tomato sauce, that is, it is used as an ingredient, it is recommended to stack 64 on top of each other in principle. Very, very trivial, but.. I think we can improve the quality of the mod by supplementing the details.

**Comment by lcy0x1** [comment]
Problem fixed in next version
