### ISSUE TITLE
Candle Cakes tag not loading due to twilightdelight candle cakes error

### ISSUE THREAD

**Issue by DelviousCrafts** [Minecraft-LightLand/Twilight-Delight#27]
I'm not sure if it was a premature addition while you're still working on the feature, or if the candle cakes just aren't registering appropriately (though I can't find mention of them in the source code at this time), but Twilight Delight candle cakes are causing the minecraft:candle_cakes block tag not to be able to load, which in turn is causing the farmersdelight:minable/knife block tag to not load, nullifying the use of knives in world. 

Versions: 
- Minecraft: 1.20.1
- Forge: 47.2.21
- Farmers Delight: 1.2.4
- Twilight Delight: 2.0.10

**Comment by ewsmith** [comment]
for anyone who want's to play with this, you can get the rest of the tags to load with [lmft](https://legacy.curseforge.com/minecraft/mc-mods/lmft)

**Comment by lcy0x1** [comment]
Will fix it

**Comment by lcy0x1** [comment]
Seems to be the problem with Neapolitan compat. I forgot to make those items tagged optionally

**Comment by lcy0x1** [comment]
Completed in 2.0.11
