### ISSUE TITLE
Incompatible with Neapolitan 1.20.1

### ISSUE THREAD

**Issue by Aci0l** [Minecraft-LightLand/Twilight-Delight#29]
The mod is referencing an old version of Neapolitan's milkshake item code, causing a crash.
[crash-2024-05-01_22.13.38-client.txt](https://github.com/Minecraft-LightLand/Twilight-Delight/files/15185329/crash-2024-05-01_22.13.38-client.txt)

**Comment by lcy0x1** [comment]
Fixed long time ago. Just update

**Comment by Aci0l** [comment]
Thanks, goat.
