### ISSUE TITLE
Twilight Delight version 1.3.0 is incompatible with Farmer's Delight version 1.2.2

### ISSUE THREAD

**Issue by Sedwert** [Minecraft-LightLand/Twilight-Delight#3]
Minecraft crashes on launch when Farmer's Delight v1.2.2 is combined with Twilight Delight v1.3.0

I'm assuming this is a Twilight Delight issue as Farmer's Delight works as intended when Twilight Delight is disabled.

Tested on a clean install of 1.19.2, forge version 43.2.0

Only mods are Twilight Forest, Twilight Delight, and Farmer's Delight

[crash-2023-07-10_16.09.55-client.txt](https://github.com/Minecraft-LightLand/Twilight-Delight/files/12009216/crash-2023-07-10_16.09.55-client.txt)

**Comment by lcy0x1** [comment]
They changed something that we need to change as well. Will fix it ASAP

**Comment by lcy0x1** [comment]
Fixed
