### ISSUE TITLE
Fiery Cooking Pot appears heated on any block

### ISSUE THREAD

**Issue by 4li77l3n00b** [Minecraft-LightLand/Twilight-Delight#30]
![2024-08-07_15 41 47](https://github.com/user-attachments/assets/867237a8-cad5-445c-9843-fe493362d29b)
![2024-08-07_15 41 49](https://github.com/user-attachments/assets/327906c6-0a9c-4ba0-9878-7771bc3f5310)

**Comment by lcy0x1** [comment]
Fiery pot auto heats itself. This is intended. After all, it’s made with fiery ingot.
