### ISSUE TITLE
[BUG][1.21.x][Neoforge] Duplicated Enchantment description

### ISSUE THREAD

**Issue by ffuentesm** [Minecraft-LightLand/Twilight-Delight#32]
twilightdelight-3.0.0+4
https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/251#issuecomment-2381325950

You can see that the description is doubled when I use the mod with Enchantment Description. 
![image](https://github.com/user-attachments/assets/bf9ae8d8-6e3f-4dd7-8043-590333b25a3a)

When I uninstall TWD the tooltip works and is not duplicated.
![image](https://github.com/user-attachments/assets/f6c5dbcd-59aa-4c2c-abe4-2994c5a40ef7)

**Comment by lcy0x1** [comment]
problem identified. Ench Desc changed how they construct text from 1.20 and broke my compat.
Fixed in 3.0.0+5, uploading

**Comment by ffuentesm** [comment]
On a side note, do you know what causes some of the effects to duplicate in the tooltips?
I notice this problem on the base FD mod, with foods having duplicated effect names. 
![image](https://github.com/user-attachments/assets/7f81783b-ce0b-4a9c-9c43-06039a0d272c)
![image](https://github.com/user-attachments/assets/19d3a892-32e5-4503-a850-58505231a276)

**Comment by lcy0x1** [comment]
Yes. Some mods adding effect tooltip to all food items.

I used to do that and then realized how stupid it is.

FD has a config option to disable its food effect tooltips and most FD addons use that config to control their own effect tooltip as well, but it could be better to identify who add tooltip to all mods.

I know abnormal's mods do that but I doubt if they are ported. Check thermal?

**Comment by ffuentesm** [comment]
Found the problem, Effect Description. I disabled the FD food effect since Effect description shows the effects of all items, even negative ones. 

But for some reason, the drinks from TWFD are not disappearing 
![image](https://github.com/user-attachments/assets/8ab9e7bf-24fb-4ce9-9b86-e95f9312c6e4)
![image](https://github.com/user-attachments/assets/cad360af-affa-44c8-829f-7811a36b2fe7)
![image](https://github.com/user-attachments/assets/5c3d279d-7dc7-4d93-a202-1b72e2a134b1)

**Comment by lcy0x1** [comment]
Cuz I forgot to add the check. Added now. Will be available in the next update. Also I need to fix the description
