### ISSUE TITLE
[1.20.1] Some Loot Tables and Recipes refering to "cake" instead of "pie"

### ISSUE THREAD

**Issue by Taschenmogul** [Minecraft-LightLand/Twilight-Delight#35]
Apparently, in twilightdelight-2.0.13, a few recipes and loot tables are erroneously refering to a "cake", when the actual block and item are called "pie" instead.
In some cases even both are present, for example "aurora_cake.json" and "aurora_pie.json". I assume that these are remnants of a past refactoring, or signs of a future one. Recipes for the "Neapolitan" integration still seem to use "cake" instead of "pie".
Just mentioning this here as a reminder, because I stumbled upon it when checking my logs.

**Comment by lcy0x1** [comment]
I don't understand. The neapolitan items are called cake, and those recipes are loaded only when neapolitan is loaded. There are no cakes outsde of that

**Comment by lcy0x1** [comment]
As for loot tables, those are for Neapolitan Twilight Cakes, which would only be valid if you have neapolitan installed.

**Comment by Taschenmogul** [comment]
Ah, now this makes sense! I was just going through my logs, trying to erase any errors and warnings. I got rid of those by overriding the data files in question, but it's good if this is actually calculated behaviour, instead of something erroneous.
Just wanted to make you aware of this, in case it were rather a bug!
