### ISSUE TITLE
delight issues?

### ISSUE THREAD

**Issue by VaporeonScripts** [Minecraft-LightLand/Twilight-Delight#36]
https://mclo.gs/6coNCmm
forge 1.20.1

**Comment by lcy0x1** [comment]
I don't see any error. What's the issue?

**Comment by VaporeonScripts** [comment]
Search for twilight delight,it should show a mixin error or sum

**Comment by lcy0x1** [comment]
Nah, those are loot table errors.

Those loot tables are for Neapolitan compat blocks (cakes). Since Neapolitan is not installed, those loot table failed to load.
