### ISSUE TITLE
Crashing 1.20.1

### ISSUE THREAD

**Issue by baronpalmer** [Minecraft-LightLand/Twilight-Delight#37]
Not sure why it's crashing as it was working fine just the other day.
[crash-2024-12-24_10.55.31-client.txt](https://github.com/user-attachments/files/18241389/crash-2024-12-24_10.55.31-client.txt)
Something to do with the thirst i'm guessing?

**Comment by lcy0x1** [comment]
Likely that you put the wrong id in thirst config
Cause of Crash: `sob:foul_berry_smoothie:`
Try to find this entry in your thirst config and remove the trailing `:`

**Comment by baronpalmer** [comment]
Ahhh, sorry! I'm an idiot! Can't believe I didn't catch that.
