### ISSUE TITLE
Missing textures in version 1.3.1 with farmer's delight 1.2.2

### ISSUE THREAD

**Issue by koppiki** [Minecraft-LightLand/Twilight-Delight#4]
![image](https://github.com/Minecraft-LightLand/Twilight-Delight/assets/96354498/dbb74955-804d-4447-a758-3957f850bfaf)

Items with missing textures are the following:
Hydra Piece
Raw Venison Rib
Cooked Venison Rib
Raw Meef Slice
Cooked Meef Slice
Raw Insect
Cooked Insect
Torchberry Cookie
Chocolate Wafer
Glowstew
Glow Venison Rib with Pasta
Fried Insect
Thousand Plant Stew
Grilled Ghast
Thorn Rose Tea
Torchberry Juice
Phytochemical Juice
Glacier Ice Tea
Aurora Ice Cream

**Comment by lcy0x1** [comment]
I don’t have this problem. Are you using Optifine?

**Comment by koppiki** [comment]
> I don’t have this problem. Are you using Optifine?

I am using rubidium currently - no optifine. I can give you my modlist if you'd like?

**Comment by lcy0x1** [comment]
Sure. Modlist will help

**Comment by lcy0x1** [comment]
I tried with Rubidium and it still works

**Comment by koppiki** [comment]
> Sure. Modlist will help

here you go- 
[Spelunking Bags (by Sweetygamer)](https://www.curseforge.com/minecraft/mc-mods/spelunking-bags)
    [Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
    [Twilight's Flavors & Delight (by lcy0x1)](https://www.curseforge.com/minecraft/mc-mods/twilights-flavors-delight)
    [Sully's Peeves (by GoesBySully)](https://www.curseforge.com/minecraft/texture-packs/sullys-peeves)
    [Combat Roll [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/combat-roll)
    [Soul fire'd (by Crystal_Spider_)](https://www.curseforge.com/minecraft/mc-mods/soul-fired)
    [Max Health Fix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
    [Stylish Effects (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/stylish-effects)
    [Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
    [FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
    [Galosphere Delight (A Farmer's Delight Add-on) (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/galosphere-delight-a-farmers-delight-add-on)
    [Ore Variants (by IcyCrystaI)](https://www.curseforge.com/minecraft/texture-packs/ore-variants)
    [Atmospheric (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/atmospheric)
    [Even Better Amethyst [Forge] (by betathunder1)](https://www.curseforge.com/minecraft/mc-mods/even-better-amethyst)
    [Create: Structures (by FusionSwarly)](https://www.curseforge.com/minecraft/mc-mods/create-structures)
    [Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
    [Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
    [Spirit (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/spirit)
    [Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
    [Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
    [Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
    [Dungeons and Taverns (by Nova_Wostra)](https://www.curseforge.com/minecraft/mc-mods/dungeon-and-taverns)
    [Incubation (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/incubation)
    [Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
    [Jade Addons (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
    [Build Guide (Forge+Fabric) (by brentmaas)](https://www.curseforge.com/minecraft/mc-mods/build-guide)
    [Echo Chest [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/echo-chest)
    [Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
    [Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
    [Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
    [Magnesium/Rubidium Extras (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
    [Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
    [MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
    [Vitalize (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/vitalize)
    [playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
    [Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
    [YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
    [NoCube's Better Smoker (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/nocubes-better-smoker)
    [Horse Expert (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/horse-expert)
    [Hexal (by Talia)](https://www.curseforge.com/minecraft/mc-mods/hexal)
    [Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
    [Undead Unleashed! (by Fredzik2)](https://www.curseforge.com/minecraft/mc-mods/undead-unleashed)
    [Hearth & Home (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/hearth-and-home)
    [Some Assembly Required (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/some-assembly-required)
    [Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
    [Aquamirae (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/ob-aquamirae)
    [Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
    [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
    [Universal Bone Meal [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/universal-bone-meal-forge)
    [Sprout (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/sprout)
    [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
    [Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
    [Neko's Enchanted Books (by Nekomaster1000)](https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books)
    [Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
    [Snail Mail (by Coda1552)](https://www.curseforge.com/minecraft/mc-mods/snail-mail)
    [Critters and Companions (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/critters-and-companions)
    [Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
    [Limited Chunkloading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading)
    [Nether's Exoticism (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/nethers-exoticism)
    [Axes Are Weapons (Fabric/Forge) (by Fourmisain)](https://www.curseforge.com/minecraft/mc-mods/axes-are-weapons)
    [Soft Weather (by vectorwing)](https://www.curseforge.com/minecraft/texture-packs/soft-weather)
    [Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
    [Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
    [Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
    [NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
    [Kiwi 🥝 (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/kiwi)
    [Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
    [Nether Depths Upgrade (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade)
    [Delightful (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/delightful)
    [Everything is Copper (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/everythingcopper)
    [Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
    [ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
    [Explorify – Dungeons & Structures (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/explorify)
    [Snuffles (by schnappdragon)](https://www.curseforge.com/minecraft/mc-mods/snuffles)
    [The Salt (by mortuusars)](https://www.curseforge.com/minecraft/mc-mods/salt)
    [Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
    [FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
    [Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
    [Effective (Forge) (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/effective-forge)
    [AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
    [Gadgets Against Grind (by MaxNeedsSnacks)](https://www.curseforge.com/minecraft/mc-mods/gag)
    [Infernal Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion)
    [FTB Backups 2 (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2)
    [Dramatic Doors (by FizzWare)](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors)
    [Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
    [Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
    [HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
    [Create: ComputerCraft (by EndRage)](https://www.curseforge.com/minecraft/texture-packs/create-computercraft)
    [Peculiars (by catscythee)](https://www.curseforge.com/minecraft/mc-mods/peculiars)
    [YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
    [AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
    [Cycle Paintings (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/cycle-paintings)
    [Equipment Compare [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/equipment-compare)
    [Toast Control (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/toast-control)
    [Sophisticated Storage (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage)
    [Dark Mode Everywhere (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere)
    [Snow! Real Magic! ⛄ (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic)
    [Create Infernal Expansion Compat (by celsiusqc)](https://www.curseforge.com/minecraft/mc-mods/create-infernal-expansion-compat)
    [Loot Journal (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/loot-journal)
    [Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
    [Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
    [Collector's Reap (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/collectors-reap)
    [Monobank (by mortuusars)](https://www.curseforge.com/minecraft/mc-mods/monobank)
    [Boatload (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/boatload)
    [Simple Enchantments (by InfernalEclipse)](https://www.curseforge.com/minecraft/mc-mods/simple-enchantments)
    [Windswept! (by rose__________________)](https://www.curseforge.com/minecraft/mc-mods/windsweptmod)
    [Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
    [Frozen Delight (A Farmer's Delight Add-on) (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/frozen-delight)
    [Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
    [Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
    [Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
    [Smaller Nether Portals (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/smaller-nether-portals)
    [Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
    [Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
    [Hourglass (by DuckyCrayfish)](https://www.curseforge.com/minecraft/mc-mods/hourglass)
    [Fire Rekindled (PBR Supported) (by Tec)](https://www.curseforge.com/minecraft/texture-packs/fire-rekindled)
    [Galosphere (by orcinus73)](https://www.curseforge.com/minecraft/mc-mods/galosphere)
    [Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
    [Redstone Pen (by wilechaote)](https://www.curseforge.com/minecraft/mc-mods/redstone-pen)
    [Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
    [Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
    [Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
    [Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
    [Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
    [Mob Plaques (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/mob-plaques)
    [Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
    [Miner's Delight + (by soytutta)](https://www.curseforge.com/minecraft/mc-mods/miners-delight-plus)
    [Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
    [xali's Enhanced Jungle Wood (by xalixilax)](https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-jungle-wood)
    [Simple Corinthium (by InfernalEclipse)](https://www.curseforge.com/minecraft/mc-mods/simple-corinthium)
    [Frozen Up (by ninnih_)](https://www.curseforge.com/minecraft/mc-mods/frozen-up)
    [Not Enough Recipe Book [NERB] (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook)
    [Serene Seasons Fix (by Or_OS)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons-fix)
    [Festive Delight (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/festive-delight)
    [Create: Alloyed (by MythrilBagels)](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)
    [Colorful Azaleas (by kekie6)](https://www.curseforge.com/minecraft/mc-mods/colorfulazaleas)
    [Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
    [Authentic Shadows (by liahim85)](https://www.curseforge.com/minecraft/texture-packs/authentic-shadows)
    [Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)
    [Texels Paintings (by builtwithtexels)](https://www.curseforge.com/minecraft/mc-mods/texels-paintings)
    [Shield Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/shield-expansion)
    [Bygone Nether (by izofar)](https://www.curseforge.com/minecraft/mc-mods/bygone-nether)
    [Upgrade Aquatic (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
    [Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
    [CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
    [Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
    [Majrusz's Enchantments (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments)
    [Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
    [PAUCAL (by petrak_at)](https://www.curseforge.com/minecraft/mc-mods/paucal)
    [Respiteful (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/respiteful)
    [It Takes a Pillage (by izofar)](https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage)
    [GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
    [Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
    [Colytra (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/colytra)
    [Floralis (by luxtracon)](https://www.curseforge.com/minecraft/mc-mods/floralis)
    [Better Tridents (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/better-tridents)
    [AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
    [Login Protection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/login-protection)
    [Construction Wand (by ThetaDev)](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
    [Clayworks (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/clayworks)
    [Majrusz's Accessories (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories)
    [FindMe (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/findme)
    [Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
    [More Mob Variants (by nyuppo)](https://www.curseforge.com/minecraft/mc-mods/more-mob-variants)
    [Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
    [Dungeons Enhanced (by Valarauko9)](https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced)
    [Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
    [Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
    [Create: Factory (by antopfr90)](https://www.curseforge.com/minecraft/mc-mods/create-factory)
    [Abnormals Delight (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/abnormals-delight)
    [YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
    [Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
    [[SBM] Cardboard Boxes (by BuiltBroken)](https://www.curseforge.com/minecraft/mc-mods/sbm-cardboardboxes)
    [Cultural Delights (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights)
    [GraveStone Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
    [Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
    [Pure Discs - Trails & Tales (Fabric/Forge) (by purejoshmc)](https://www.curseforge.com/minecraft/mc-mods/pure-discs-trails-tales-fabric-forge)
    [MC style paintings (by salvad0r666)](https://www.curseforge.com/minecraft/mc-mods/minecraft-style-paintings)
    [Chalk (by mortuusars)](https://www.curseforge.com/minecraft/mc-mods/chalk)
    [PolyLib (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/polylib)
    [Create: Crystal Clear (by singularity_cyvack)](https://www.curseforge.com/minecraft/mc-mods/create-crystal-clear)
    [Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
    [Nether's Cruelty (by Sweetygamer)](https://www.curseforge.com/minecraft/mc-mods/nethers-cruelty)
    [Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
    [Hex Casting (by petrak_at)](https://www.curseforge.com/minecraft/mc-mods/hexcasting)
    [Aileron (by egshels)](https://www.curseforge.com/minecraft/mc-mods/aileron)
    [Buzzier Bees (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/buzzier-bees)
    [Environmental (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/environmental)
    [Obscure API (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/obscure-api)
    [Horse Combat Controls (by pitbox46)](https://www.curseforge.com/minecraft/mc-mods/horse-combat-controls)
    [Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
    [Chef's Delight [Forge] (by redstone3game)](https://www.curseforge.com/minecraft/mc-mods/chefs-delight-forge)
    [The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
    [Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
    [Berry Good (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/berry-good)
    [Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
    [Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
    [Creatures and Beasts (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts)
    [Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
    [FancyMenu [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge)
    [Geophilic – Biome Overhauls (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/geophilic)
    [Suggestion Provider Fix (by HarleyOConnor)](https://www.curseforge.com/minecraft/mc-mods/suggestion-provider-fix)
    [Majrusz Library (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majrusz-library)
    [Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
    [Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
    [FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
    [Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
    [Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
    [Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
    [Chimes (by BlewberryPie)](https://www.curseforge.com/minecraft/mc-mods/chimes)
    [Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
    [Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
    [Autumnity (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/autumnity)
    [CC:C Bridge (by Sammy_echt)](https://www.curseforge.com/minecraft/mc-mods/cccbridge)
    [Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
    [Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
    [Overflowing Bars [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/overflowing-bars)
    [Aqua Combat (by FaerMinded)](https://www.curseforge.com/minecraft/mc-mods/aqua-combat)
    [NoCube's Better Grindstone (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/nocubes-better-grindstone)
    [Immersive Weathering [FORGE] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge)
    [Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
    [Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
    [Controllable (Forge) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/controllable)
    [Second Chance (Forge) (by HellionGames)](https://www.curseforge.com/minecraft/mc-mods/second-chance-forge)
    [Brewin' And Chewin' (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin)
    [Dungeons Plus (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/dungeons-plus)
    [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
    [Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
    [Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
    [Create Style Modded Compats (by wedge1453)](https://www.curseforge.com/minecraft/texture-packs/create-style-modded-compats)
    [Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
    [Le Fishe Exotique Au Chocolat (by sammysemicolon)](https://www.curseforge.com/minecraft/mc-mods/le-fishe-exotique-au-chocolat)
    [Good Ending (by orcinus73)](https://www.curseforge.com/minecraft/mc-mods/good-ending)
    [NoCube's Chinchillas (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/nocubes-chinchillas)
    [Neapolitan (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/neapolitan)
    [Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
    [spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
    [Nullscape (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/nullscape)
    [Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
    [Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
    [Eating Animations+ (by frogbirdd)](https://www.curseforge.com/minecraft/texture-packs/eating-animations)
    [Blossom (by yurisuika)](https://www.curseforge.com/minecraft/mc-mods/blossom)
    [Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)

**Comment by lcy0x1** [comment]
That’s a lot of mods… could you help me to reduce the number of suspects?

remove some of the mods and start the game. If the problem persists, then those mods are fine. If not, then one of those mods are the problem. I will test Flywheel and Oculus

**Comment by lcy0x1** [comment]
I have Flywheel, Oculus, Rubidium, Create, Oculus-Flywheel Compat, and now I can't start game. What version should I use?

**Comment by lcy0x1** [comment]
I checked Rubidium + Oculus + Oculus-Flywheel Compat + Create (which should have Flywheel embedded) and it works fine. Please help me to reduce the range of potential problematic mods

**Comment by koppiki** [comment]
> I checked Rubidium + Oculus + Oculus-Flywheel Compat + Create (which should have Flywheel embedded) and it works fine. Please help me to reduce the range of potential problematic mods

I will do this and get back to you

**Comment by lcy0x1** [comment]
Also, it could be that some shaders are breaking things. Try loading game without shaders

**Comment by koppiki** [comment]
> Also, it could be that some shaders are breaking things. Try loading game without shaders

I already did that, and it didn't help (you're right that it's a good thing to check, though)

**Comment by koppiki** [comment]
I figured it out-
it's this pack.
https://www.curseforge.com/minecraft/texture-packs/eating-animations

it seems it overrides some of the textures in a way that doesn't work. If I remove it it works fine. Sorry about wasting your time here, since it's not your fault at all.
