### ISSUE TITLE
Neapolitan updated recently and appears to have broken this mod

### ISSUE THREAD

**Issue by Traehgniw** [Minecraft-LightLand/Twilight-Delight#6]
It changed milkshakes to use the flavour's effect and not a custom effect. This mod now crashes the game on startup with an error related to milkshake effects. Going back a version fixes it.

**Comment by lcy0x1** [comment]
I thought I have fixed compat issues in 1.4.1. Does it update again?

**Comment by Traehgniw** [comment]
The 1.19.2 version crashes with Neapolitian's October 6 update

**Comment by lcy0x1** [comment]
Make sure you are using twilightdelight-1.4.1, and if you are, send me latest.log

**Comment by Traehgniw** [comment]
Twilight Delight 1.4.1 does not appear to be released.

**Comment by lcy0x1** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/twilights-flavors-delight/files/4802144

**Comment by Traehgniw** [comment]
Oh it's on Curseforge I was looking on Modrinth

**Comment by lcy0x1** [comment]
You can always add blocks to tags through Datapack or KubeJs

**Comment by drakray** [comment]
There seem to be a crash with the new version for Forge 1.20.1
https://pastebin.com/nZvcnA0i
<details>

```
	Suppressed: net.minecraftforge.fml.ModLoadingException: Twilight's Flavor & Delight (twilightdelight) encountered an error during the common_setup event phase
§7java.lang.NoSuchMethodError: 'void com.teamabnormals.neapolitan.common.item.MilkshakeItem.<init>(net.minecraft.world.effect.MobEffectCategory, net.minecraft.world.item.Item$Properties)'
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:155) ~[language-java-47.2.2.jar%23878!/:47.2] {}
		at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:346) ~[core-47.2.2.jar%23877!/:47.2] {}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}

```

</details>

**Comment by lcy0x1** [comment]
> There seem to be a crash with the new version for Forge 1.20.1
> https://pastebin.com/nZvcnA0i

Wow, Neapolitan updated to 1.20.1? I need to work on compat for it to be compatible. I will update it ASAP

**Comment by lcy0x1** [comment]
@drakray I can't find Neapolitan for 1.20.1 in CurseForge but I see that in your modlist. Where do you get it?

**Comment by lcy0x1** [comment]
Ah, it seems that they are in beta release, so I don't have access to it. Technically gating beta release for money is breaking mojang's EULA but anyway

**Comment by lcy0x1** [comment]
Just got the beta and fixed it.
